# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cuMO6pmxCHRa2Y05PTGGy6qUNyBfAPd
"""

import streamlit as st
import pandas as pd
import pickle
import os
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------------------------
# Page Configuration
# -------------------------------------------------
st.set_page_config(
    page_title="Heart Disease Prediction App",
    layout="wide"
)

# -------------------------------------------------
# Title & Subtitle
# -------------------------------------------------
st.markdown(
    "<h1 style='color:#1f2937'>❤️ Heart Disease Prediction App</h1>",
    unsafe_allow_html=True
)
st.markdown(
    "Upload test data, select a model, and view performance metrics."
)

# -------------------------------------------------
# Load Evaluation Results
# -------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
EVAL_PATH = os.path.join(BASE_DIR, "model", "evaluation_results.pkl")

if not os.path.exists(EVAL_PATH):
    st.error(f"evaluation_results.pkl not found at: {EVAL_PATH}")
    st.stop()

with open(EVAL_PATH, "rb") as f:
    EVAL_RESULTS = pickle.load(f)

# -------------------------------------------------
# Upload CSV
# -------------------------------------------------
st.markdown("### 📂 Upload test CSV file (with `num` column)")

uploaded_file = st.file_uploader(
    "Upload CSV file",
    type=["csv"]
)

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.markdown("### 📄 Uploaded Dataset Preview")
    st.dataframe(data.head())

# -------------------------------------------------
# Model Selection
# -------------------------------------------------
st.markdown("### 🎯 Model Selection")

model_names = list(EVAL_RESULTS.keys())

selected_model = st.selectbox(
    "Choose a model",
    model_names
)

run_btn = st.button("Run Prediction")

# -------------------------------------------------
# Show Results ONLY After Button Click
# -------------------------------------------------
if run_btn:

    st.markdown("---")

    # =================================================
    # Evaluation Metrics
    # =================================================
    st.markdown("## 📊 Evaluation Metrics")

    metrics = EVAL_RESULTS[selected_model]["metrics"]

    col1, col2, col3 = st.columns(3)
    col1.metric("Accuracy", round(metrics["accuracy"], 3))
    col2.metric("Precision", round(metrics["precision"], 3))
    col3.metric("Recall", round(metrics["recall"], 3))

    col4, col5, col6 = st.columns(3)
    col4.metric("F1 Score", round(metrics["f1"], 3))
    col5.metric("MCC", round(metrics["mcc"], 3))
    col6.metric(
        "AUC",
        round(metrics["auc"], 3) if metrics["auc"] is not None else "N/A"
    )

    # =================================================
    # Confusion Matrix
    # =================================================
    st.markdown("## 🧩 Confusion Matrix")

    cm = EVAL_RESULTS[selected_model]["confusion_matrix"]

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        ax=ax
    )
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    st.pyplot(fig)

    # =================================================
    # Classification Report
    # =================================================
    st.markdown("## 📄 Classification Report")
    st.text(EVAL_RESULTS[selected_model]["classification_report"])